server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital-document-delivery-system
    username: postgres
    password: $eQuE$aDa4002
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWT_SECRET}
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    url: /v1/api-docs
    path: /swagger-ui.html
