server:
  port: 8082
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5433/digital-document-delivery-system?sslmode=disable}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    url: /v1/api-docs
    path: /swagger-ui.html
jwt:
  secret: XZJVERVevwMLOofmwemfwVMERINEIMWOEMFWOEFM34T34653e3RTBn2232323ewfeIVNRIRG3FO9i9g34OKMHMKLQP3233j3onfwdEKVWEFMWkwvwew
