spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8080
          predicates:
            - Path=/v1/auth/**
        - id: users-route
          uri: http://localhost:8082
          predicates:
            - Path=/v1/user/**
        - id: letters-route
          uri: http://localhost:8083
          predicates:
            - Path=/v1/letter/**
        - id: packages-route
          uri: http://localhost:8084
          predicates:
            - Path=/v1/package/**
        - id: notification-route
          uri: http://localhost:8086
          predicates:
            - Path=/v1/notification/**
  endpoints:
    web:
      exposure:
        includes: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
server:
  port: 8081
jwt:
  secret: XZJVERVevwMLOofmwemfwVMERINEIMWOEMFWOEFM34T34653e3RTBn2232323ewfeIVNRIRG3FO9i9g34OKMHMKLQP3233j3onfwdEKVWEFMWkwvwew
