spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8080
          predicates:
            - Path=/v1/auth/**
        - id: users-route
          uri: http://localhost:8082
          predicates:
            - Path=/v1/user/**
          filters:
            - AuthenticationFilter
        - id: letters-route
          uri: http://localhost:8083
          predicates:
            - Path=/v1/letter/**
          filters:
            - AuthenticationFilter
        - id: packages-route
          uri: http://localhost:8084
          predicates:
            - Path=/v1/package/**
          filters:
            - AuthenticationFilter
  endpoints:
    web:
      exposure:
        includes: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
server:
  port: 8081
